services:
  # docker-gtasa_alternative_code
  docker-benlib:
    build: 
      context: archlinux
      dockerfile: Dockerfile
      args:
        - USERNAME=bensuperpc
    container_name: docker-gtasa_alternative_code
    #user: ${PUID:-1000}:${PGID:-1000}
    user: bensuperpc
    #profiles:
    #  - docker-gtasa_alternative_code
    restart: on-failure:3
    #env_file:
    #  - ./zola/env/zola.env
    working_dir: /work
    command: /bin/sh -c "while sleep 1000; do :; done"
    #ports:
    #  - "80:80"
    volumes:
      - ./../:/work:cached
      - build_tmpfs:/work/build:rw
    networks:
      - gtasa_alternative_code-network
      # Disable due devcontainer build error
    #security_opt:
    #  - no-new-privileges:true
    #read_only: true
    #cap_drop:
    #  - SYS_ADMIN
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.001'
          memory: 20M

networks:
  gtasa_alternative_code-network:
    driver: bridge
    name: gtasa_alternative_code-network

volumes:
  build_tmpfs:
    name: build_tmpfs
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=1g,uid=${PUID:-1000},gid=${PGID:-1000}