option(ENABLE_CCACHE "Use ccache to speed up compilation process" ON)

if(ENABLE_CCACHE)
  find_program(CCACHE_PATH ccache)
  if(CCACHE_PATH)
    message(STATUS "Using ccache at ${CCACHE_PATH}")
    set(CMAKE_C_COMPILER_LAUNCHER ${CCACHE_PATH})
    set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE_PATH})
  else()
    message(STATUS "Could not find ccache")
  endif()
endif()
