#include <QtQml/qqmlextensionplugin.h>

// Generated by Qt
extern void qml_register_types_AppLib();
Q_GHS_KEEP_REFERENCE(qml_register_types_AppLib)

class AppLibPlugin : public QQmlEngineExtensionPlugin {
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

   public:
    AppLibPlugin(QObject* parent = nullptr) : QQmlEngineExtensionPlugin(parent) {
        volatile auto registration = &qml_register_types_AppLib;
        Q_UNUSED(registration)
    }

    // Automatically register providers and handlers
    void initializeEngine(QQmlEngine* engine, const char* uri) final {
        Q_UNUSED(uri);
    }
};

#include "AppLibplugin_AppLibPlugin.moc"
